=== scriptella/scriptella-etl/trunk/core/src/conf/scriptella/dtd/scriptella.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
%
 Copyright 2006 The Scriptella Project Team.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
%
@title Script File DTD
-->

<!--
The scripts is the root element of Scriptella XML file.
-->
<!ELEMENT scripts (description?, properties?, connection*, (script*, query*)*)>
<!ATTLIST scripts>

<!--
Contains description of scripts file.
-->
<!ELEMENT description (#PCDATA)>
<!--
The properties element contains a set of properties available for script elements.
The content of this element conforms to format supported by java.util.Properties.
This element may contain plain text or includes.
-->
<!ELEMENT properties (#PCDATA | include)*>
<!--
The connection element specifies connection to a database or other jdbc component.
This element may contain properties as plain text with includes.
Example:
%
<connection id="in" driver="com.octetstring.jdbcLdap.sql.JdbcLdapDriver"
            url="jdbc:ldap://localhost:389/dc=scriptella"
            user="cn=root,dc=scriptella" password="secret">
    SEARCH_SCOPE=subTreeScope
    ignore_transactions=true
</connection>
%
-->
<!ELEMENT connection (#PCDATA | include)*>
<!--
 @attr id connection identifier. Used in scripts and queries
 @attr driver driver class
 @attr url jdbc url
 @attr user database login
 @attr password database password
 @attr catalog catalog
 @attr schema - schema
-->
<!ATTLIST connection
id ID #IMPLIED
driver CDATA #REQUIRED
url CDATA #REQUIRED
user CDATA #REQUIRED
password CDATA #REQUIRED
catalog CDATA #IMPLIED
schema CDATA #IMPLIED
>
<!--
The fallback element contains alternate content to be used if the requested resource cannot be found.
This element may contain plain text or includes.
Example:
%
<include href="http://no-such-url/file.txt">
    <fallback>Failed to retrieve full text</fallback>
</include>
%
-->
<!ELEMENT fallback (#PCDATA | include)*>
<!ATTLIST fallback>

<!--
The include element specifies content to include. Concept similar to XInclude.
This element may contain plain text, includes or fallbacks.
-->
<!ELEMENT include (fallback?)>
<!--
@attr href contains an URL pointing to the file to include
-->
<!ATTLIST include
href CDATA #REQUIRED
>
<!--
The dialect element defines a database specific SQL. SQL elements may contain any number of nested dialects.
This element may contain plain text or includes.
-->
<!ELEMENT dialect (#PCDATA | include)*>
<!--
 @attr database - case insensitive regular expression to match database vendor name, e.g. .*oracle.*
 @attr version - case insensitive regular expression to match database version, e.g. 1\.0
-->
<!ATTLIST dialect
database CDATA #IMPLIED
version CDATA #IMPLIED
>
<!--
The query element is used to specify a query producing a result set.
This element may contain queries, scripts, plain text, includes and dialects.
-->
<!ELEMENT query (#PCDATA | include | dialect | query | script)*>
<!--
 @attr connection-id references connection by identifier. The value of this attribute is inherited for nested elements.
 @attr if expression to test. If result of evaluation is true - the element is evaluated, otherwise skipped.
-->
<!ATTLIST query
connection-id IDREF #IMPLIED
if CDATA #IMPLIED
>

<!--
The script element is used to specify an SQL script.
This element may contain plain text, includes and dialects.
-->

<!ELEMENT script (#PCDATA | include | dialect)*>
<!--
 @attr connection-id references connection by identifier. The value of this attribute is inherited for nested elements.
 @attr new-tx true if a new transaction(and extra JDBC connection) is required for this element.
 @attr if expression to test. If result of evaluation is true - the element is evaluated, otherwise skipped.

-->
<!ATTLIST script
connection-id IDREF #IMPLIED
new-tx (true | false) "false"
if CDATA #IMPLIED
>

=== scriptella/scriptella-etl/trunk/samples/ldap/ldap2db.xml
<!DOCTYPE scripts SYSTEM "scriptella.dtd">
<scripts>
    <description>
        Migrates data from LDAP to Database.
        Creates users and roles tables suitable for Tomcat JDBCRealm authentication.
        The source data is obtained from LDAP.
    </description>
    <connection id="in" driver="com.octetstring.jdbcLdap.sql.JdbcLdapDriver"
                url="jdbc:ldap://localhost:389/dc=scriptella?SEARCH_SCOPE:=subTreeScope&amp;ignore_transactions:=true"
                user="cn=root,dc=scriptella" password="secret"/>
    <connection id="out" driver="org.hsqldb.jdbcDriver" url="jdbc:hsqldb:file:outdb" user="sa" password=""/>
    <script connection-id="out">
        <!--Creates empty database -->
        <include href="dbschema.sql"/>
    </script>
    <query connection-id="in">
        <!--Selects users-->
        SELECT uid,userPassword,DN FROM ou=people WHERE objectClass = 'inetOrgPerson'
        <script connection-id="out">
            INSERT INTO Users VALUES ($uid, $userPassword);
        </script>
        <query>
            SELECT cn FROM ou=groups WHERE objectClass = 'groupOfUniqueNames' and uniqueMember=$DN
            <script connection-id="out">
                INSERT INTO User_Roles VALUES ($uid, $cn);
            </script>
        </query>
    </query>
    <script connection-id="out">
        <!-- Just to shutdown HSQL correctly -->
        COMMIT;
        SHUTDOWN;
    </script>
</scripts>

=== scriptella/scriptella-etl/trunk/samples/export/script.xml
<!DOCTYPE scripts SYSTEM "scriptella.dtd">
<scripts>
    <connection id="in" driver="org.hsqldb.jdbcDriver" url="jdbc:hsqldb:mem:indb" user="sa" password=""/>
    <connection id="out" driver="org.hsqldb.jdbcDriver" url="jdbc:hsqldb:file:outdb" user="sa" password=""/>
    <script connection-id="in">
        CREATE TABLE Test (<include href="fields.sql"/>);

        insert into Test(id, text) values (1, 'One');
    </script>
    <script connection-id="out">
        CREATE TEXT TABLE Test (<include href="fields.sql"/>);
        SET TABLE Test SOURCE "result.csv"
    </script>

    <query connection-id="in">
        select * from test
        <script connection-id="out">
            insert into Test(id, text) values ($id, $text);
        </script>
    </query>

    <script connection-id="out"><!-- Correctly shutdown the DB -->
        COMMIT;
        SHUTDOWN;
    </script>
</scripts>

=== scriptella/scriptella-etl/trunk/core/src/test/resources/DialectsTest2.xml
<!DOCTYPE scripts SYSTEM "scriptella.dtd">
<scripts>
    <connection driver="org.hsqldb.jdbcDriver" url="jdbc:hsqldb:mem:dialectstest2" user="sa" password=""/>
    <script>
        <!--must execute-->
        CREATE TABLE Test (
        ID INT
        );
        insert into test values (1);
        insert into test values (2);
        insert into test values (3);
        CREATE TABLE Test2 (
        ID INT
        );
    </script>
    <query>
        select * from test where id=1
        <script>
            <dialect database="FOO"><!--Skipped-->
                insert into test2 values (3);
            </dialect>
            insert into test2 values (${ID});
        </script>
    </query>

    <query>
        <script>
            insert into test2 values (${ID});
        </script>
        <dialect database="HSQL.*"><!--executes-->
            select * from test where id=2;
        </dialect>
        <dialect database=".*oracle.*"><!--Skipped-->
            select * from test where id=3
        </dialect>
    </query>

    <script><!--Skipped but not failed-->
        <dialect database="FOO">
            select * from test2
        </dialect>
    </script>

</scripts>

=== scriptella/scriptella-etl/trunk/samples/csv/csv2db.xml
<!DOCTYPE scripts SYSTEM "scriptella.dtd">
<scripts>
    <description>
        Export data from table to CSV file.
    </description>
    <connection id="in" driver="org.hsqldb.jdbcDriver" url="jdbc:hsqldb:file:tmp" user="sa" password=""/>
    <connection id="out" driver="org.hsqldb.jdbcDriver" url="jdbc:hsqldb:file:db" user="sa" password=""/>
    <script connection-id="in">
        <!-- Creates TEXT table to output CSV data -->
        CREATE TEXT TABLE Bug (
            <include href="fields.sql"/>
        );
        <!--Specify file to store table results -->
        SET TABLE Bug SOURCE "bugs-in.csv";
    </script>
    <script connection-id="out">
        <!-- Creates Bug table to output CSV data -->
        DROP TABLE BUG IF EXISTS;
        CREATE TABLE Bug (
            <include href="fields.sql"/>
        );
    </script>

    <query connection-id="in">
        <!--Selects all bugs -->
        SELECT * from Bug
        <script connection-id="out">
            INSERT INTO Bug VALUES (?ID, ?priority, ?summary, ?status);
        </script>
    </query>

    <script connection-id="out"><!-- Correctly shutdown the DB -->
        COMMIT;
        SHUTDOWN;
    </script>
    <script connection-id="in"><!-- Correctly shutdown the DB -->
        COMMIT;
        SHUTDOWN;
    </script>

</scripts>

=== scriptella/scriptella-etl/trunk/samples/import/script.xml
<!DOCTYPE scripts SYSTEM "scriptella.dtd">
<scripts>
    <connection id="in" driver="org.hsqldb.jdbcDriver" url="jdbc:hsqldb:file:indb" user="sa" password=""/>
    <connection id="out" driver="org.hsqldb.jdbcDriver" url="jdbc:hsqldb:file:outdb" user="sa" password=""/>
    <script connection-id="in">
        CREATE TEXT TABLE Test (
        ID INT,
        TEXT VARCHAR(100)
        );
        SET TABLE Test SOURCE "in.csv"
    </script>
    <script connection-id="out">
        CREATE TEXT TABLE Test (
        ID INT,
        TEXT VARCHAR(100)
        );
        SET TABLE Test SOURCE "out.csv;fs=|"
    </script>

    <query connection-id="in">
        select * from test
        <script connection-id="out">
            insert into Test(id, text) values ($id*10, $text);
        </script>
    </query>
    <!-- Just for HSQLDB graceful shutdown -->
    <script connection-id="in">
        shutdown;
    </script>
    <script connection-id="out">
        shutdown;
    </script>
</scripts>

=== scriptella/scriptella-etl/trunk/core/src/test/resources/DialectsTest.xml
<!DOCTYPE scripts SYSTEM "scriptella.dtd">
<scripts>
    <connection driver="org.hsqldb.jdbcDriver" url="jdbc:hsqldb:mem:dialectstest" user="sa" password=""/>
    <script>
        <!--must execute-->
        CREATE TABLE Test (
        ID INT,
        VALUE VARCHAR(255)
        );
    </script>
    <script>
        <!--must execute-->
        insert into test(id, value) values (1,'222');
    </script>
    <script>
        <dialect database=".*oracle.*">
            insert into test(id, value) values (2,'333');
        </dialect>
    </script>
    <script>
        <dialect database="hsql.*"><!--must execute-->
            insert into test(id, value) values (3,'333');
        </dialect>
        <dialect><!--skipped-->
            insert into test(id, value) values (4,'333');
        </dialect>
        <dialect database=""><!--skipped-->
            insert into test(id, value) values (33,'333');
        </dialect>

    </script>
    <script>
        <dialect><!--must execute-->
            insert into test(id, value) values (5,'333');
        </dialect>
    </script>
    <script>
        <dialect database="HSQL.*" version="1\.8\..*"><!--must execute-->
            insert into test(id, value) values (6,'333');
        </dialect>
        <dialect><!--skipped-->
            insert into test(id, value) values (7,'333');
        </dialect>

    </script>


</scripts>

=== scriptella/scriptella-etl/trunk/core/src/test/resources/XIncludeTest.xml
<!DOCTYPE scripts SYSTEM "scriptella.dtd">
<scripts>
    <connection driver="---" url="---" user="" password=""/>
    <script>
        <include href="XIncludeTest.sql"/>
    </script>
    <script>
        <include href="xinctst/XIncludeTest.sql"/>
    </script>
    <script>
        --Sample1--
        <include href="XIncludeTest.sql"/>
        --Sample2--
    </script>
    <script>
        <include href="nosuchurl">
            <fallback>Fallback!</fallback>
        </include>
    </script>


</scripts>

=== scriptella/scriptella-etl/trunk/drivers/src/test/scriptella/driver/h2/H2ScriptTest.xml
<!DOCTYPE scripts SYSTEM "scriptella.dtd">
<scripts>
    <description>
        Simply creates a table with data in one db and copy it to another H2 database.
    </description>
    <connection id="c1" driver="h2" user="sa" password=""/>
    <connection id="c2" driver="org.h2.Driver" url="jdbc:h2:mem:tst"/>
    <script connection-id="c1">
        CREATE TABLE Test (
        ID INT,
        Data BLOB
        );
        insert into Test values (1, '01010101');
        insert into Test values (2, '02020202');
        insert into Test values (3, '03030303');
    </script>
    <script connection-id="c2">
        CREATE TABLE Test (
            ID INT,
            Data BLOB
        );
    </script>
    <query connection-id="c1">
        SELECT * FROM Test
        <script connection-id="c2">
            INSERT INTO Test VALUES (?1, ?2);
        </script>
    </query>

</scripts>
